spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - "*"
            allowedHeaders: "*"
      routes:
        - id: frontend-service
          uri: http://localhost:3000
          predicates:
            - Path=/**